### ISSUE TITLE
In FUN(X[[i]], ...) : NAs introduced by coercion

### ISSUE THREAD

**Issue by LeuteMatthias** [fcocquemas/rdatastream#6]
Dear François,
I have the following problem and would highly appreciate your help:

When I try to retrieve non-numerical data with the ds() function, the following warning message is issued: _In FUN(X[[i]], ...) : NAs introduced by coercion_

Below is a simple example for a single firm. Here the last variable (SOPRDP0011) is of unit type Y/N, which appears to cause the introduction of NAs.

```
Firm <- c(960338)
Variables <- c("SOCSCORE", "SOPR", "SOPRDP0011")

x <- ds(user, securities = Firm, fields = Variables, fromDate = "2002-12-31", toDate = "2015-12-31", period = "Y")["Data",1]
x

```
The output looks like this:
![screen shot 2017-04-19 at 2 18 15 pm](https://cloud.githubusercontent.com/assets/25764046/25179646/13ae9a76-250b-11e7-94df-659ac3b22069.png)

Many thanks in advance,
Matthias Leute

**Comment by fcocquemas** [comment]
Hello Matthias,

Thanks for bringing this to my attention. As it appears, the problem is that RDatastream tries to convert the fields to numeric values. That should indeed work for most, but fails in this instance.

I'm thinking about the best way to approach this, and whether type "detection" is worth it.

As a temporary workaround, you could just do the request with `asDataFrame=FALSE` and extract that variable manually:

    dt <- ds(user, securities = Firm, fields = Variables, fromDate = "2002-12-31", toDate = "2015-12-31", period = "Y", asDataFrame=FALSE)
    x[[1]]$SOPRDP0011 <- unlist(dt["Fields",][[1]]$SOPRDP0011)
    x

Let me know if this helps!

Best,
François

**Comment by LeuteMatthias** [comment]
Hello François,
first of all thank you very much for your fast response and help!
The proposed solution helps me already in that I can retrieve data. Since I have over 400 variables that I want to retrieve for about 3000 companies  I simply looped your proposed solution for every variable and after some trial and error it works for my data structure.

For anyone having the same issue, this worked for me:

```
  df <- ds(user, securities = Firms, fields = Variables, fromDate = "2002-12-31", toDate = "2015-12-31", period = "Y")["Data",1]
  bug_fix <- ds(user, securities = Firms[1], fields = Variables, fromDate = "2002-12-31", toDate = "2015-12-31", period = "Y", asDataFrame=FALSE) # necessary for loop
  for (j in 1:n){ # loop to work-around bug of non-numerics being NAs for firm 1 only
    df[[1]][4+j] <- unlist(bug_fix["Fields",][[1]][4+j])
  }
```

This is only for firm 1 of course. Can easily be adjusted to firm i.


Thanks a lot,
Matthias :)

**Comment by fcocquemas** [comment]
Hello Matthias,

The latest version of the package should have fixed your problem.

It's really a one-function change. I came across function `type.convert`, which should detect the type of each variable appropriately rather than try to coerce it to a numeric.

Thanks for the bug report! Please reopen if you find something that does not work appropriately.

Best,
François
